In [1]:
# %load 11_pandas_intro.py
# View more python tutorials on my Youtube and Youku channel!!!

# Youtube video tutorial: https://www.youtube.com/channel/UCdyjiB5H8Pu7aDTNVXTTpcg
# Youku video tutorial: http://i.youku.com/pythontutorial

"""
Please note, this code is only for python 3+. If you are using python 2+, please modify the code accordingly.
"""
from __future__ import print_function
import pandas as pd
import numpy as np

s = pd.Series([1,3,6,np.nan,4,1]) # similar with 1D numpy
print(s)


0    1.0
1    3.0
2    6.0
3    NaN
4    4.0
5    1.0
dtype: float64


In [3]:
dates = pd.date_range('20160101', periods=6)
print(dates)


DatetimeIndex(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
               '2016-01-05', '2016-01-06'],
              dtype='datetime64[ns]', freq='D')


In [4]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=['A','B','C','D'])
print(df['B'])


2016-01-01   -0.530248
2016-01-02    0.079806
2016-01-03   -0.837939
2016-01-04   -0.810422
2016-01-05   -0.523229
2016-01-06   -2.087428
Freq: D, Name: B, dtype: float64


In [6]:
df2 = pd.DataFrame({'A' : 1.,
                       'B' : pd.Timestamp('20130102'),
                        'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                        'D' : np.array([3] * 4,dtype='int32'),
                        'E' : pd.Categorical(["test","train","test","train"]),
                        'F' : 'foo'})
print(df2)


     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo


In [7]:
print(df2.dtypes)


A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object


In [8]:
print(df.index)


DatetimeIndex(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
               '2016-01-05', '2016-01-06'],
              dtype='datetime64[ns]', freq='D')


In [9]:
print(df.columns)


Index(['A', 'B', 'C', 'D'], dtype='object')


In [10]:
print(df.values)


[[ 0.71174565 -0.53024754 -1.09930151 -0.76098414]
 [ 0.76854034  0.07980578 -0.46297308  0.77134299]
 [ 0.16293817 -0.83793897  2.60874061 -0.58018907]
 [ 0.66516158 -0.81042242  0.31629897 -1.06404342]
 [ 0.15150743 -0.52322858  0.58126868  0.0358434 ]
 [-1.54585523 -2.08742808  1.21236119  1.60061   ]]


In [11]:
print(df.describe())


              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.152340 -0.784910  0.526066  0.000430
std    0.876311  0.718482  1.301968  1.020403
min   -1.545855 -2.087428 -1.099302 -1.064043
25%    0.154365 -0.831060 -0.268155 -0.715785
50%    0.414050 -0.670335  0.448784 -0.272173
75%    0.700100 -0.524983  1.054588  0.587468
max    0.768540  0.079806  2.608741  1.600610


In [12]:
print(df.T)


   2016-01-01  2016-01-02  2016-01-03  2016-01-04  2016-01-05  2016-01-06
A    0.711746    0.768540    0.162938    0.665162    0.151507   -1.545855
B   -0.530248    0.079806   -0.837939   -0.810422   -0.523229   -2.087428
C   -1.099302   -0.462973    2.608741    0.316299    0.581269    1.212361
D   -0.760984    0.771343   -0.580189   -1.064043    0.035843    1.600610


In [13]:
print(df.sort_index(axis=1, ascending=False))


                   D         C         B         A
2016-01-01 -0.760984 -1.099302 -0.530248  0.711746
2016-01-02  0.771343 -0.462973  0.079806  0.768540
2016-01-03 -0.580189  2.608741 -0.837939  0.162938
2016-01-04 -1.064043  0.316299 -0.810422  0.665162
2016-01-05  0.035843  0.581269 -0.523229  0.151507
2016-01-06  1.600610  1.212361 -2.087428 -1.545855


In [14]:
print(df.sort_values(by='B'))

                   A         B         C         D
2016-01-06 -1.545855 -2.087428  1.212361  1.600610
2016-01-03  0.162938 -0.837939  2.608741 -0.580189
2016-01-04  0.665162 -0.810422  0.316299 -1.064043
2016-01-01  0.711746 -0.530248 -1.099302 -0.760984
2016-01-05  0.151507 -0.523229  0.581269  0.035843
2016-01-02  0.768540  0.079806 -0.462973  0.771343
