In [51]:
import pandas as pd
import numpy as np

# 利用pandas读取Excel    
df = pd.read_excel(r'.\data.xlsx',sheet_name= 'Sheet2', header= 0)
# print(df)
fields = df.columns.values #获取列索引向量（对有表头的方式，是表头标签向量），返回类型为ndarray（一维）。
df.index.values #获取行索引向量，返回类型为ndarray（一维）
# print(fields)
df_list = df.values # 获取全部数据，返回类型为ndarray（二维）
# print(df_list)
data =np.matrix(df_list)
# print(data)
# df['类别'].astype('string')
df1 = df.loc[df['类别'] == 1] #筛选出列值等于标量的行，用==
df2 = df.loc[df['类别'] == 2]
df3 = df.loc[df['类别'] == 3]
print(df1.values[0:5,2:4])
print('--------')
print(df1.values[0:5,2:4].astype(float))
print('--------')
print(np.array(df1.values[0:5,2:4]))
# print(df2.values)
# print(df3.values)
# print(data)
# print(data.shape)
# k = data.shape[1]-2

[[73.74 0.33]
 [72.73 0.58]
 [72.44 1.62]
 [71.28 1.37]
 [77.42 0.52]]
--------
[[73.74  0.33]
 [72.73  0.58]
 [72.44  1.62]
 [71.28  1.37]
 [77.42  0.52]]
--------
[[73.74 0.33]
 [72.73 0.58]
 [72.44 1.62]
 [71.28 1.37]
 [77.42 0.52]]
