创建一个边界值为1而内部都是0的数组，图例如下：
[提示：]解此题可以先把所有值都设置为1，这是大正方形；其次，把边界除外小正方形全部设置为0。
本题用到numpy的切片原理。多维数组同样遵循x[start:stop:step]的原理。

In [9]:
import numpy as np
S = np.zeros((10, 10))
S[1:2, 1:3] = 10
print(S)
np.concatenate()

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 10. 10.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


在数组主对角线上创建一个值为1,2,3,4的5x5矩阵，图例如下：

[1 0 0 0]
[0 2 0 0]
[0 0 3 0]
[0 0 0 4]

In [3]:
import numpy as np
S = np.diag((1,2,3,4))
print(S)


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


数组归一化操作
生成一个随机的5*5矩阵，找出最大值和最小值，然后把最大值和最小值分别用1和0表示，其他值则介于在0和1中间。

In [12]:
import numpy as np
S = np.random.random((5, 5))
Smax, Smin = S.max(),S.min()
print(Smax,Smin)
S = (S - Smin)/(Smax - Smin)
print(S)

0.879942108239877 0.07997399792726512
[[0.16363832 0.77332538 0.68935672 0.86095561 0.51471162]
 [0.63808429 0.34227039 0.68609114 0.52165813 0.26447568]
 [0.75749969 0.         0.08232841 0.99794847 0.06804807]
 [0.94709302 0.33257775 0.62453006 0.09020606 0.10212197]
 [0.79575081 0.00439006 0.05821886 0.6920039  1.        ]]


In [13]:
import numpy as np
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.30477125 -0.4211269  -0.09259288 -1.64245385 -1.08570187]
 [-0.66314137 -0.7357838   1.25231318 -0.25952665  0.69044076]
 [ 1.17490935 -0.06561305 -0.1325724   1.50249813 -1.0410199 ]
 [ 0.67169024 -0.43980145  0.33015797  0.95632442 -1.66609061]
 [ 1.77140736  0.99776932 -0.82880617  1.04820272 -1.62625379]]


In [17]:
a = np.ones((2,3,4),dtype=np.int)
b = a.reshape(3,8)
b


C:\Users\xyt55\AppData\Local\Temp\ipykernel_22380\2943881188.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.ones((2,3,4),dtype=np.int)


array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])