创建一个边界值为1而内部都是0的数组，图例如下：
[提示：]解此题可以先把所有值都设置为1，这是大正方形；其次，把边界除外小正方形全部设置为0。
本题用到numpy的切片原理。多维数组同样遵循x[start:stop:step]的原理。

In [1]:
import numpy as np
S = np.ones((10, 10))
S[1:9, 1:9] = 0
print(S)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


在数组主对角线上创建一个值为1,2,3,4的5x5矩阵，图例如下：

[1 0 0 0]
[0 2 0 0]
[0 0 3 0]
[0 0 0 4]

In [3]:
import numpy as np
S = np.diag((1,2,3,4))
print(S)


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


数组归一化操作
生成一个随机的5*5矩阵，找出最大值和最小值，然后把最大值和最小值分别用1和0表示，其他值则介于在0和1中间。

In [4]:
import numpy as np
S = np.random.random((5, 5))
Smax, Smin = S.max(),S.min()
S = (S - Smin)/(Smax - Smin)
print(S)

[[0.72722343 0.19413673 0.79058919 1.         0.94523128]
 [0.78044759 0.3087531  0.72562593 0.55215145 0.        ]
 [0.08885615 0.68254631 0.28785959 0.47219576 0.02238411]
 [0.08318769 0.41299086 0.74332256 0.50133798 0.55064104]
 [0.32763527 0.14453692 0.05696847 0.56693027 0.79934709]]
