In [1]:
# %load 数组的索引和切片.py
'''
一维NumPy数组的索引与python列表的索引相同
二维数组的索引在单个或者多个轴向上完成，在某一轴上与一维数组索引相同
'''
import numpy as np

a=np.arange(12).reshape(3,4)
print('数组a为')
print(a)

数组a为
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [2]:
print('a[0]=',a[0])    #第0行
print('a[1]=',a[1])
print('a[0][0]=',a[0][0])
print('a[1][2]=',a[1][2])
a[1]=666
print("数组a已经被修改,修改后为")
print(a)
a[0][0]=111
print(a)

a[0]= [0 1 2 3]
a[1]= [4 5 6 7]
a[0][0]= 0
a[1][2]= 6
数组a已经被修改,修改后为
[[  0   1   2   3]
 [666 666 666 666]
 [  8   9  10  11]]
[[111   1   2   3]
 [666 666 666 666]
 [  8   9  10  11]]


In [3]:

#一维数组切片
b=np.arange(12)
print('b=',b)
print('b[1:3]=',b[1:3])
print('b[1:7:2]=',b[1:7:2])
print('b[9:]=',b[9:])
print('b[:]=',b[:])

b= [ 0  1  2  3  4  5  6  7  8  9 10 11]
b[1:3]= [1 2]
b[1:7:2]= [1 3 5]
b[9:]= [ 9 10 11]
b[:]= [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [4]:

#二维数组切片
c=np.arange(12).reshape(3,4)
print('c=',c)
'''
二维数组切片取得是两个区间的的交集
'''
print('c[0:2][1:3]=',c[0:2][1:3])
print('c[2:][:2]=',c[2:][1:2])  #####
print('c[:]=',c[:])

'''
布尔型索引是指使用布尔数组来索引目标数组，以此来找出与布尔数组中值为
true的对应的目标数组中的数据
'''
#布尔数组的长度必须与目标数组对应的轴的长度一致
names=np.array(['赵','王','李','上官','公孙','顿山'])
data=np.random.randn(6,3)
print(data)
print('上官对应的行：',data[names=='上官'])

d=np.arange(12).reshape(3,4)
print(d)
print('d>5',d>5)
print('d[d>5]',d[d>5])


#花式索引


c= [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
c[0:2][1:3]= [[4 5 6 7]]
c[2:][:2]= []
c[:]= [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 2.04250336  0.24610106  0.59541105]
 [ 0.42178772 -0.33956219  0.47875794]
 [-0.16740292  0.13333651  1.06035468]
 [ 0.45694818 -0.83546635 -1.4118287 ]
 [ 0.86574002 -1.17014785 -0.5206115 ]
 [ 0.6228534  -1.02939711  0.22163649]]
上官对应的行： [[ 0.45694818 -0.83546635 -1.4118287 ]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
d>5 [[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
d[d>5] [ 6  7  8  9 10 11]
