# Python 科学计算库Numpy
## 1- Numpy 概述

笔记：
- 第一点: 要给数组中的每个元素都加1，
'''
    array = [1,2,3,4]          #会出现该错误，can only concatenate list (not "int") to list：只能将列表（不是“int”）连接到列表
    array + 1
'''
要全部将矩阵的加操作全部转换为底层，numpy.ndarray :<class 'numpy.ndarray'>
'''
    array = np.array([1,2,3,4])
    print(type(array))             #<class 'numpy.ndarray'>
'''
- 第二点
- 第三点

In [1]:
import numpy as np
array = np.array([1,2,3,4])
print(type(array))
print(array)
# print(help(np.mean))

<class 'numpy.ndarray'>
[1 2 3 4]


In [2]:
array2 = array + 1               # 在ARRAY 数组中，对每一个向量都进行了一个加1操作，他会对每一个数进行加1 操作
print(array2)

[2 3 4 5]


In [3]:
array2 = array + 2              # 在ARRAY 数组中，对每一个向量都进行了一个加1操作，他会对每一个数进行加1 操作
print(array2)

[3 4 5 6]


In [4]:
array[2]                       # 取数据操作

3

In [5]:
array

array([1, 2, 3, 4])

In [6]:
array.shape

(4,)

In [7]:
import numpy as np
from numpy import array 

array3 = np.array([[1,2,3],[4,5,6]])          #几个【】就代表说几维数组
# array3                          #查看数组含有两个样本，即为两行，三列：每个样本有三个特征
array3.shape                    # 用array.shape 可以查看数组的行列    ：(2, 3)
print(array3)
print(array3[1:])

[[1 2 3]
 [4 5 6]]
[[4 5 6]]


In [8]:
import numpy as np
from numpy import array 

array4 = np.array([[1,2,3],[4,5,6],[7,8,9]])          #几个【】就代表说几维数组
# array3                          #查看数组含有两个样本，即为两行，三列：每个样本有三个特征
print(array4.shape)                    # 用array.shape 可以查看数组的行列    ：(2, 3)
print(array4)
print(array4[2:])
print(array4.ndim)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]]
2


In [9]:
x = np.array([[[1,1], [2,2], [3,3]], [[1,1], [1,1], [1,1]]])
print(x)
print(x.ndim)

[[[1 1]
  [2 2]
  [3 3]]

 [[1 1]
  [1 1]
  [1 1]]]
3


# Array 结构

笔记：
-  第一点：对于ndarray结构来说，里面所有的元素必须是同一类型的，如果不是的话，会自动向下转换

In [10]:
# 笔记第一点:对于ndarray结构来说，里面所有的元素必须是同一类型的，如果不是的话，会自动向下转换
tang_list = [1.0,2,3,4,5]
tang_array = np.array(tang_list)
tang_array


array([1., 2., 3., 4., 5.])

ndarray 基本属性操作
- 第一点
- 第二点


In [11]:
print(type(tang_array))

<class 'numpy.ndarray'>


In [12]:
tang_array.dtype

dtype('float64')

In [13]:
tang_array.itemsize  # 输出nparray结构中元素所占的字节数

8

In [14]:
tang_array.shape

(5,)

In [15]:
tang_array.size           # 查看一下共有多少个元素

5

In [16]:
np.size(tang_array)

5

In [17]:
np.shape(tang_array)

(5,)

In [18]:
tang_array.ndim                       # 查看数组的维度，数组为一维的

1

In [19]:
tang_array

array([1., 2., 3., 4., 5.])

In [20]:
tang_array.fill(0)                  # 用0 进行填充数组 ： tang_array.fill(0)
tang_array

array([0., 0., 0., 0., 0.])

笔记：
- 第一点：索引 与切片：跟Python 都是一样的，还是从0 开始

In [21]:
tang_list = [1,2,3,4,5]
tang_array = np.array(tang_list)
tang_array[1]

2

In [22]:
tang_array[1:3]             # 切出来的 包含前面一个tang_array[1]，不包含最后面一个tang_array[3]    

array([2, 3])

In [23]:
tang_array[-1]                 # 查询最后一个数组的元素，同样可以用-1 来表示

5

In [24]:
tang_array[-2:]                  # 查询倒数第二个数组元素到最后一个

array([4, 5])

矩阵的格式（多维的形式）

In [25]:
tang_array = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
tang_array
#tang_array.ndim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
tang_array.shape

(3, 3)

In [27]:
tang_array.size            # 一共有多少个数据

9

In [28]:
tang_array.ndim              #二维数组

2

In [29]:
tang_array[1,2]              # 取出多维数组中的数据,需要指定索引

6

# 不同的赋值操作

In [30]:
tang_array2 = tang_array              # 采用的是 =  号复制，即tang_array2 和tang_array 指向的是内存的同一块区域，
                                   # 只要修改了两个中的任何一个，另一个就会改变
tang_array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
tang_array2[1,1] = 100
tang_array2


array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [32]:
tang_array[1]                 # 取出第二行

array([  4, 100,   6])

In [33]:
tang_array[:,1]              # 取出所有的行中的第二列的值

array([  2, 100,   8])

In [34]:
tang_array

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [35]:
tang_array2 = tang_array.copy()               # 采用这种方法，就可以使 二者以后指向不同的区域
tang_array2

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [36]:
tang_array2[1,1] = 5
tang_array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
tang_array

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

# 2-array 结构

In [38]:
tang_array = np.arange(0,100,10)         # 0：代表从0 开始，100： 代表到100 结束， 10 ：代表等间隔的间距
tang_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
mask = np.array([0,0,0,0,0,0,1,1,1,1],dtype = bool)          # 重新做一个数组，将大于60 分的学生认为是好学生，标记为1， 
                                                      # 默认情况下,dtype 值为int类型，此处设置为布尔类型,dtype = bool
mask                                          # 掩码， 此处可以认为是布尔类型的索引

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [40]:
tang_array[mask]                             # 就会将 布尔值为True 的值拿出来，进行筛选

array([60, 70, 80, 90])

In [41]:
import os
print(os.path.abspath('.'))

D:\Big_Data_Test\numpy&pandas\Numpy


In [42]:
random_array = np.random.rand(10)             # 构建一个随机数组含有10 个数值
random_array

array([0.64921604, 0.93404206, 0.96620291, 0.94129778, 0.20873496,
       0.61703953, 0.83757561, 0.01796839, 0.40381042, 0.88793546])

In [43]:
mask = random_array > 0.5                         # 布尔类型的判断方法
mask

array([ True,  True,  True,  True, False,  True,  True, False, False,
        True])

In [44]:
tang_array[mask]


array([ 0, 10, 20, 30, 50, 60, 90])

In [45]:
tang_array2 = np.array([10,20,30,40,50,60])        # 布尔类型的判断方法
tang_array2 > 30


array([False, False, False,  True,  True,  True])

In [46]:
np.where(tang_array2 > 30)                        # 找到正确的得索引，不要True ,Fause

(array([3, 4, 5], dtype=int64),)

In [47]:
tang_array2[np.where(tang_array2 > 30)]            # 找到正确的大于30 分的人， 并且取出对应的分数

array([40, 50, 60])

In [48]:
tang_array2 = np.array([1,2,3,4,5],dtype = np.float32)            # 改变一下数据类型
tang_array2

array([1., 2., 3., 4., 5.], dtype=float32)

In [49]:
tang_array3 = np.array([1,2,3,4,'str'],dtype = np.object)           # 数组中含有int ，str类型的数据，只能指定为object 类型
tang_array3

C:\Users\xyt556\AppData\Local\Temp\ipykernel_30796\2696021407.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  tang_array3 = np.array([1,2,3,4,'str'],dtype = np.object)           # 数组中含有int ，str类型的数据，只能指定为object 类型


array([1, 2, 3, 4, 'str'], dtype=object)

In [50]:
tang_array2.astype(np.float32)               # 修改数据类型

array([1., 2., 3., 4., 5.], dtype=float32)

In [51]:
tang_array2

array([1., 2., 3., 4., 5.], dtype=float32)

# 3 - 数值计算

In [52]:
import numpy as np

tang_arr = np.array([[1,2,3],[4,5,6]])
tang_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
np.sum(tang_arr)               # 将数组中所有的元素都相加

21

笔记： 指定要进行的操作是沿着什么轴（维度）

In [54]:
np.sum(tang_arr,axis = 0)                # 指定轴为 0, 列相加

array([5, 7, 9])

In [55]:
np.sum(tang_arr,axis = 1)             #指定轴为 1，行相加

array([ 6, 15])

In [56]:
tang_arr.sum(axis = -1)            # 也可以这样调用SUM 函数

array([ 6, 15])

In [57]:
tang_arr.prod(axis = 0)              #每一列执行相乘的操作

array([ 4, 10, 18])

In [58]:
tang_arr.min()                   # 查找数组中的最小值的操作

1

In [59]:
tang_arr.min(axis = 0)                  # 查找每一列的最小值

array([1, 2, 3])

In [60]:
tang_arr.prod(axis = 1)         # 每一行的乘积

array([  6, 120])

找到索引位置

In [61]:
tang_arr.argmin()            # 找到所有的数中最小的数的索引

0

In [62]:
tang_arr.argmax()               # 找到所有的数中最大的数的索引

5

In [63]:
tang_arr.argmin(axis = 0)           # 好到每一列的最小的数的索引

array([0, 0, 0], dtype=int64)

In [64]:
tang_arr.mean()                      # 平均值

3.5

In [65]:
tang_arr.var()                      # 方差的计算

2.9166666666666665

In [66]:
tang_arr.std()                     # 标准差的计算

1.707825127659933

In [67]:
tang_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
tang_arr.clip(2,4)           #截断操作，小的 用2 补 ，大得 用4补

array([[2, 2, 3],
       [4, 4, 4]])

In [69]:
tang_array2  =  np.array([2.23,3.56,5.67])
tang_array2

array([2.23, 3.56, 5.67])

In [70]:
tang_array2.round()             # 四舍五入，没有小数，round()函数中没有任何参数

array([2., 4., 6.])

In [71]:
tang_array2.round(1)             # 四舍五入，含有一个小数点，小数点后精确到多少位

array([2.2, 3.6, 5.7])

In [72]:
tang_array2.round(decimals = 1)      # 还可以这样写上参数的名字

array([2.2, 3.6, 5.7])

# 4 -  排序

In [73]:
import numpy as np

tang_array4 = np.array([[1.5,3.7,5.3],
                        [4.5,7.8,1.2]])
tang_array4

array([[1.5, 3.7, 5.3],
       [4.5, 7.8, 1.2]])

In [74]:
np.sort(tang_array4)                 # 默认的排序是按照样本数据中从小到大的顺序排列

array([[1.5, 3.7, 5.3],
       [1.2, 4.5, 7.8]])

In [75]:
np.sort(tang_array4,axis = 0)         # 按列中从小到大排列

array([[1.5, 3.7, 1.2],
       [4.5, 7.8, 5.3]])

In [76]:
tang_array4

array([[1.5, 3.7, 5.3],
       [4.5, 7.8, 1.2]])

In [77]:
np.argsort(tang_array4)

array([[0, 1, 2],
       [2, 0, 1]], dtype=int64)

In [78]:
tang_array4[1,2] = 2.5
tang_array4

array([[1.5, 3.7, 5.3],
       [4.5, 7.8, 2.5]])

In [79]:
np.argsort(tang_array4,axis=1)                    # 函数argsort()  可以查找排序后的索引

array([[0, 1, 2],
       [2, 0, 1]], dtype=int64)

In [80]:
tang_array4 = np.linspace(0,10,10)             # linspace（）函数， 第二个10 代表着等间隔的构建10个数据 
tang_array4 

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [81]:
values = np.array([2.5,6.5,9.5])              # 想把数据插入到我们的数据当中，
print(np.searchsorted(tang_array4,values))      # searchsorted （）找到当前的队伍插进去，tang_array4 ：代表着当前队伍，values; 代表着要插进去的值
print(tang_array4)

[3 6 9]
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


#   升序降序排列

In [82]:
tang_array5 = np.array([[1,2,5],
                      [5,4,2],              # 重新定义一个新的数组：二维
                      [2,9,3],
                       [1,7,4]])
tang_array5

array([[1, 2, 5],
       [5, 4, 2],
       [2, 9, 3],
       [1, 7, 4]])

In [83]:
index = np.lexsort([-1*tang_array5[:,0],tang_array5[:,2]])         # 第一列：指定降序的为-1， 第三列：升序 为什么都不指定
index

array([1, 2, 3, 0], dtype=int64)

In [84]:
tang_array_5 = tang_array5[index]                  # 按数组的index 进行排列，并输出
tang_array_5

array([[5, 4, 2],
       [2, 9, 3],
       [1, 7, 4],
       [1, 2, 5]])

# 5 - 数组形状操作

In [85]:
tang_array6 = np.arange(10)
tang_array6                                 # 此时输出的数组为一行10 列，要改变为2 * 5 的矩阵

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
tang_array6.shape                       
tang_array6.shape = 2,5                    # 存在10 个数，需要改变一下shape 的值,变为两个样本，5 个特征值
tang_array6

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [87]:
tang_array6.shape

(2, 5)

In [88]:
tang_array6.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [89]:
tang_array6.shape = 1,10

In [90]:
tang_array6

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [91]:
tang_array6 = tang_array6[np.newaxis:,]        # 添加一个新的轴
tang_array6.shape
tang_array6

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [92]:
tang_array6 = tang_array.squeeze()                # 进行压缩，将没有元素的轴去掉
tang_array6.shape
tang_array6

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [93]:
tang_array6.shape = 2,5
tang_array6

array([[ 0, 10, 20, 30, 40],
       [50, 60, 70, 80, 90]])

In [94]:
tang_array6.transpose()            # 矩阵的转置   .T

array([[ 0, 50],
       [10, 60],
       [20, 70],
       [30, 80],
       [40, 90]])

# 数组的连接

In [95]:
import numpy as np
a = np.array([[123,456,678],[3214,456,134]])
a

array([[ 123,  456,  678],
       [3214,  456,  134]])

In [96]:
b = np.array([[1235,3214,432],[43,13,134]])
b 

array([[1235, 3214,  432],
       [  43,   13,  134]])

In [97]:
c = np.concatenate((a,b))           # concatenate() 函数，将A,B 两个数组连接起来：np.concatenate((a,b)) = np.concatenate((a,b)，axis = 0) 
c                                   # 可以组合不同样本的相同特征

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3214,  432],
       [  43,   13,  134]])

In [98]:
C = np.concatenate((a,b),axis = 1)               # 横着连接：每行的数据进行连接,此时可以组合同一个样本的不同特征
C

array([[ 123,  456,  678, 1235, 3214,  432],
       [3214,  456,  134,   43,   13,  134]])

In [99]:
C.shape

(2, 6)

In [100]:
np.vstack((a,b))                              # 竖着连接：

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3214,  432],
       [  43,   13,  134]])

In [101]:
np.hstack((a,b))                         # 横着连接：

array([[ 123,  456,  678, 1235, 3214,  432],
       [3214,  456,  134,   43,   13,  134]])

In [102]:
a.flatten()                        # 拉长操作

array([ 123,  456,  678, 3214,  456,  134])

In [103]:
a.ravel()

array([ 123,  456,  678, 3214,  456,  134])

# 6 - 数组生成

In [104]:
zjy_array6_1 = np.array([1,2,3])
zjy_array6_1

array([1, 2, 3])

In [105]:
zjy_array6_2 = np.array(10)
zjy_array6_2

array(10)

In [106]:
zjy_array6_3 = np.arange(2,20,2)
zjy_array6_3

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

默认以10 为底

In [107]:
np.logspace(0,1,5)        # 从0 开始，到1 结束，等距离的5 个数

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

更常用的zeros ones

In [108]:
np.zeros(3)      # 3 代表的是矩阵的维度

array([0., 0., 0.])

In [109]:
np.zeros((3,3))    # 构建一个二维的矩阵，全为0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [110]:
np.ones((3,3))              # 构建一个二维的，三行三列的矩阵，全为1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [111]:
np.ones((3,3)) * 8

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

In [112]:
a = np.empty(6)
a                              #array([0., 0., 0., 0., 0., 0.])
a.shape                # （6，）

(6,)

In [113]:
a.fill(1)
a

array([1., 1., 1., 1., 1., 1.])

# 7 - 运算

In [114]:
import numpy as np

x = np.array([5,5])        #  x,y 皆为一维数组
y = np.array([2,2])

np.multiply(x,y)                     # multiply（）函数，两个数组相乘

array([10, 10])

# 一维的时候 ，是内积

In [115]:
np.dot(x,y)             # dot() 函数，如果数组为一维数组的话，就是 两个数组的内积，（对应的位置相乘再相加）

20

In [116]:
x.shape

(2,)

# 二维的时候 就是矩阵之间的相乘

In [117]:
y.shape

(2,)

In [118]:
x.shape=2,1                      # 修改shape 值
x.shape

(2, 1)

In [119]:
y.shape=1,2                   # 修改shape值
y.shape

(1, 2)

In [120]:
print(x.shape)
print(y.shape)

(2, 1)
(1, 2)


In [121]:
np.dot(x,y)

array([[10, 10],
       [10, 10]])

In [122]:
print(x)
print(y)

[[5]
 [5]]
[[2 2]]


In [123]:
x = np.array([1,1,1,4])
y = np.array([1,1,1,0])
x == y

array([ True,  True,  True, False])

In [124]:
np.logical_and(x,y)

array([ True,  True,  True, False])

In [125]:
np.logical_or(x,y)

array([ True,  True,  True,  True])

In [126]:
np.logical_not(x,y)

array([0, 0, 0, 0])

# 8 - 随机模块

Numpy 随机模块

In [127]:
import numpy as np

# 默认情况下，所有的值都是从0 到1
np.random.rand(3,2)           # 传进来的是，shape 的值

array([[0.92463585, 0.33344437],
       [0.33688696, 0.64543546],
       [0.6221614 , 0.27490743]])

In [128]:
# 返回的是随机的整数，左闭右开
np.random.randint(10,size = (5,4))

array([[9, 9, 3, 7],
       [3, 2, 4, 3],
       [6, 9, 8, 3],
       [6, 7, 1, 7],
       [0, 3, 1, 2]])

In [129]:
np.random.rand()

0.7704810611280986

In [130]:
np.random.random_sample()                # 随机进行一个采样

0.35274683204087187

In [131]:
np.random.randint(0,10,3)              # 产生从0 开始，到10 之间的整形随机数，3个

array([1, 3, 2])

# 常用随机高斯初始化操作，需要告诉均值

In [132]:
mu,sigma = 0,0.1
np.random.normal(mu,sigma,10)

array([ 0.03912877,  0.01063012,  0.0899938 ,  0.01203601, -0.08358986,
        0.24276712,  0.02519222,  0.10603957, -0.02251385, -0.08412314])

# 改变一下精度
np.set_printoptions(precision = 2)

mu,sigma = 0,0.1
np.random.normal(mu,sigma,10)

# 洗牌操作    作用;打乱原有的数据排列（有规律）

In [133]:
tang_array = np.arange(10)
tang_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
np.random.shuffle(tang_array)                      # shuffle(tang_array)函数对tang_array 数组进行洗牌操作，乱序排列
tang_array

array([3, 7, 9, 0, 4, 8, 1, 6, 2, 5])

# 随机种子

In [135]:
np.random.seed(100)
mu,sigma = 0,0.1
np.random.normal(mu,sigma,10)

array([-0.17497655,  0.03426804,  0.11530358, -0.0252436 ,  0.09813208,
        0.05142188,  0.02211797, -0.10700433, -0.01894958,  0.02550014])

In [136]:
print(help(np.random.seed))

Help on built-in function seed:

seed(...) method of numpy.random.mtrand.RandomState instance
    seed(self, seed=None)
    
    Reseed a legacy MT19937 BitGenerator
    
    Notes
    -----
    This is a convenience, legacy function.
    
    The best practice is to **not** reseed a BitGenerator, rather to
    recreate a new one. This method is here for legacy reasons.
    This example demonstrates best practice.
    
    >>> from numpy.random import MT19937
    >>> from numpy.random import RandomState, SeedSequence
    >>> rs = RandomState(MT19937(SeedSequence(123456789)))
    # Later, you want to restart the stream
    >>> rs = RandomState(MT19937(SeedSequence(987654321)))

None


#  9 -  读写

# 使用Numpy 读写数据

In [137]:
import numpy as np 
%matplotlib inline

In [138]:
%%writefile tang.txt
1 2 3 4 5 6
2 3 5 8 7 9

Overwriting tang.txt


In [139]:
data = []
with open('tang.txt') as f:
    for line in f.readlines():
        fields = line.split()
        cur_data = [float(x) for x in fields]                 # 用python读取太麻烦了，可以用Numpy包来解决
        data.append(cur_data)
data = np.array(data)
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

#  ' tang2.txt': 路径最好和代码放到一起
skiprows : 去掉第几行
delimiter = ',': 分隔符
usercols = (0,1,4): 指定使用那一列

In [140]:
data = np.loadtxt('tang.txt')                # 加载 .txt 文件,同样可以实现，并且是以 空格为分隔符
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

In [141]:
%%writefile tang2.txt
1,2,3,4,5,6
2,3,5,7,9,8

Overwriting tang2.txt


In [142]:
data = np.loadtxt('tang2.txt',delimiter = ',')            # delimiter = ','   : 代表是以 ， 为分隔符
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 7., 9., 8.]])

In [143]:
%%writefile tang3.txt
x,y,z,w,a,b
1,2,3,4,5,6
2,3,5,7,9,8

Overwriting tang3.txt


In [144]:
data = np.loadtxt('tang3.txt',delimiter = ',',skiprows = 1)      # skiprows = 1   : 代表第一行就不要了 
                                             #但是此时如果 数据第一行与 %% writefile tang3.txt 之间有空行的话，就会报错
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 7., 9., 8.]])

# 以下几种为保存的方法 

In [145]:
np.savetxt('tang4.txt',tang_array,fmt = '%d')
print(help(np.save))

Help on function save in module numpy:

save(file, arr, allow_pickle=True, fix_imports=True)
    Save an array to a binary file in NumPy ``.npy`` format.
    
    Parameters
    ----------
    file : file, str, or pathlib.Path
        File or filename to which the data is saved.  If file is a file-object,
        then the filename is unchanged.  If file is a string or Path, a ``.npy``
        extension will be appended to the filename if it does not already
        have one.
    arr : array_like
        Array data to be saved.
    allow_pickle : bool, optional
        Allow saving object arrays using Python pickles. Reasons for disallowing
        pickles include security (loading pickled data can execute arbitrary
        code) and portability (pickled objects may not be loadable on different
        Python installations, for example if the stored objects require libraries
        that are not available, and not all pickled data is compatible between
        Python 2 and Python 3).
  

In [146]:
np.savetxt('tang4.txt',tang_array,fmt = '%d',delimiter = ',')

In [147]:
np.savetxt('tang4.txt',tang_array,fmt = '%.2f',delimiter = ',')

#   读 array 结构

In [148]:
tang_array = np.array([[1,2,3],[4,5,6]])
np.save('tang_array.npy',tang_array)                   # 直接将数组保存下来，.npy 格式

In [149]:
tang_array = np.load('tang_array.npy')              # 加载.npy 文件
tang_array

array([[1, 2, 3],
       [4, 5, 6]])

In [150]:
tang_array2 = np.arange(10)
tang_array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])