In [4]:
import numpy as np


In [9]:
a=np.array([0,1,2,3,4])
b=np.array([9,8,7,6,5])
# c=a**2+b**3
c =  a**2 + b**3
c

array([729, 513, 347, 225, 141])

In [10]:
d=a*b
d


array([ 0,  8, 14, 18, 20])

In [14]:
b1 = np.array([[9],[8],[7],[6],[5]])
b1

array([[9],
       [8],
       [7],
       [6],
       [5]])

In [15]:
d1=a*b
d1

array([ 0,  8, 14, 18, 20])

数组相乘：n1分别与n2的每一行相乘，得到的数组与n2的结构相同

数组点乘：n1的每一行乘以n2的每一列，类似于矩阵相乘

In [17]:
import numpy as np
#创建数组
n1 = np.array([1, 2, 3])
n2= np.array([[3, 5, 2], [1, 8, 4], [9, 0, 3]])
print(n1)
print(n2)
print('数组相乘结果为：','\n', n1*n2) #数组相乘
print('数组点乘结果为：','\n', np.dot(n1, n2)) #数组点乘

[1 2 3]
[[3 5 2]
 [1 8 4]
 [9 0 3]]
数组相乘结果为： 
 [[ 3 10  6]
 [ 1 16 12]
 [ 9  0  9]]
数组点乘结果为： 
 [32 21 19]


In [19]:
import numpy as np
n1 = np.mat('1 3 3;4 5 6;7 12 9') # #创建矩阵，使用分号隔开数据
n2 = np.mat('2 6 6;8 10 12;14 24 18')
print(n1)
print(n2)
print('矩阵相乘结果为：\n',n1*n2)  #矩阵相乘
print('矩阵对应元素相乘结果为：\n',np.multiply(n1,n2))

[[ 1  3  3]
 [ 4  5  6]
 [ 7 12  9]]
[[ 2  6  6]
 [ 8 10 12]
 [14 24 18]]
矩阵相乘结果为：
 [[ 68 108  96]
 [132 218 192]
 [236 378 348]]
矩阵对应元素相乘结果为：
 [[  2  18  18]
 [ 32  50  72]
 [ 98 288 162]]
